appveyor.yml

Encrypting Nuget API value

---

src/Vlingo.Wire.Tests/Message/AbstractMessageTool.cs
src/Vlingo.Wire.Tests/Message/ByteBufferPoolTest.cs
src/Vlingo.Wire.Tests/Message/PublisherAvailabilityTest.cs
src/Vlingo.Wire.Tests/Multicast/MulticastTest.cs
src/Vlingo.Wire.Tests/Node/MockConfiguration.cs
src/Vlingo.Wire/Channel/IChannelReaderConsumer.cs
src/Vlingo.Wire/Message/BasicConsumerByteBuffer.cs
src/Vlingo.Wire/Message/ByteBufferPool.cs
src/Vlingo.Wire/Message/Converters.cs
src/Vlingo.Wire/Message/IConsumerByteBuffer.cs
src/Vlingo.Wire/Message/MessagePartsBuilder.cs
src/Vlingo.Wire/Message/PublisherAvailability.cs
src/Vlingo.Wire/Message/RawMessage.cs
src/Vlingo.Wire/Message/RawMessageBuilder.cs
src/Vlingo.Wire/Message/RawMessageHeader.cs
src/Vlingo.Wire/Multicast/Group.cs
src/Vlingo.Wire/Node/Address.cs
src/Vlingo.Wire/Node/Host.cs
src/Vlingo.Wire/Node/Id.cs
src/Vlingo.Wire/Node/Name.cs
src/Vlingo.Wire/Node/Node.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Work in progress. Porting basic features for Messages.

Implementing all necessary classes for messages

---

src/Vlingo.Wire.Tests/Multicast/MulticastTest.cs
src/Vlingo.Wire/Channel/ChannelMessageDispatcher.cs
src/Vlingo.Wire/Channel/IChannelPublisher.cs
src/Vlingo.Wire/Channel/IChannelReader.cs
src/Vlingo.Wire/Channel/MockChannelReaderConsumer.cs
src/Vlingo.Wire/Message/Converters.cs
src/Vlingo.Wire/Message/RawMessage.cs
src/Vlingo.Wire/Message/RawMessageBuilder.cs
src/Vlingo.Wire/Message/RawMessageHeader.cs
src/Vlingo.Wire/Multicast/MulticastPublisherReader.cs
src/Vlingo.Wire/Multicast/MulticastSubscriber.cs

Now that I'm done with basic Message definitions I'm going to work on multicast in this PR.

[WIP] Implementation of multicast

---

src/Vlingo.Wire.Tests/Channel/MockChannelReader.cs
src/Vlingo.Wire.Tests/Fdx/Inbound/InboundSocketChannelTest.cs
src/Vlingo.Wire.Tests/Fdx/Inbound/InboundStreamTest.cs
src/Vlingo.Wire.Tests/Fdx/Inbound/MockInboundStreamInterest.cs
src/Vlingo.Wire/Channel/ChannelMessageDispatcher.cs
src/Vlingo.Wire/Channel/IRequestChannelConsumer.cs
src/Vlingo.Wire/Channel/IResponseChannelConsumer.cs
src/Vlingo.Wire/Channel/SelectionReader.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorActor.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorPipelineActor.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionReader.cs
src/Vlingo.Wire/Channel/StreamExtensions.cs
src/Vlingo.Wire/Fdx/Bidirectional/ClientRequestResponseChannel.cs
src/Vlingo.Wire/Fdx/Bidirectional/ServerRequestResponseChannelActor.cs
src/Vlingo.Wire/Fdx/Inbound/IInboundClientReference.cs
src/Vlingo.Wire/Fdx/Inbound/IInboundResponder.cs
src/Vlingo.Wire/Fdx/Inbound/IInboundStreamInterest.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStream.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStreamActor.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStream__Proxy.cs
src/Vlingo.Wire/Fdx/Inbound/SocketChannelInboundReader.cs
src/Vlingo.Wire/Fdx/Outbound/IManagedOutboundChannel.cs
src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannel.cs
src/Vlingo.Wire/Message/RawMessage.cs
src/Vlingo.Wire/Message/RawMessageBuilder.cs
src/Vlingo.Wire/Message/RawMessageHeader.cs
src/Vlingo.Wire/Multicast/MulticastPublisherReader.cs

This PR will contain changes related to the implementation of full-duplex inbound features and unit tests

Implementation of full-duplex inbound

---

src/Vlingo.Wire.Tests/Channel/SocketChannelWriterTest.cs
src/Vlingo.Wire.Tests/Converter.cs
src/Vlingo.Wire.Tests/Fdx/Bidirectional/SocketRequestResponseChannelTest.cs
src/Vlingo.Wire.Tests/Fdx/Inbound/InboundSocketChannelTest.cs
src/Vlingo.Wire.Tests/Fdx/Inbound/InboundStreamTest.cs
src/Vlingo.Wire.Tests/Fdx/Outbound/ManagedOutboundSocketChannelProviderTest.cs
src/Vlingo.Wire.Tests/Fdx/Outbound/ManagedOutboundSocketChannelTest.cs
src/Vlingo.Wire.Tests/Fdx/Outbound/MockManagedOutboundChannel.cs
src/Vlingo.Wire.Tests/Fdx/Outbound/MockManagedOutboundChannelProvider.cs
src/Vlingo.Wire.Tests/Fdx/Outbound/OutboundTest.cs
src/Vlingo.Wire.Tests/Message/ByteBufferPoolTest.cs
src/Vlingo.Wire.Tests/Message/PublisherAvailabilityTest.cs
src/Vlingo.Wire.Tests/Multicast/MulticastTest.cs
src/Vlingo.Wire.Tests/Node/AddressTest.cs
src/Vlingo.Wire.Tests/Node/IdTest.cs
src/Vlingo.Wire.Tests/Node/NameTests.cs
src/Vlingo.Wire.Tests/Node/NodeTest.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorActor.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorPipelineActor.cs
src/Vlingo.Wire/Channel/SocketChannelWriter.cs
src/Vlingo.Wire/Fdx/Bidirectional/ServerRequestResponseChannelActor.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStreamActor.cs
src/Vlingo.Wire/Fdx/Outbound/IManagedOutboundChannelProvider.cs
src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannelProvider.cs
src/Vlingo.Wire/Fdx/Outbound/Outbound.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

WIP on full-duplex outbound features

Implementation of full-duplex outbound

---

src/Vlingo.Wire/Message/IMessage.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Add public marker interface IMessage and bump package version

---

src/Vlingo.Wire/Fdx/Outbound/ApplicationOutboundStreamActor.cs
src/Vlingo.Wire/Fdx/Outbound/ApplicationOutboundStream__Proxy.cs
src/Vlingo.Wire/Fdx/Outbound/IApplicationOutboundStream.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Fix fixes the #17 because it is necessary for the `vlingo-net-cluster`

Implement IApplicationOutboundStream and related classes

---

src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannelProvider.cs
src/Vlingo.Wire/Node/AddressType.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

In order to check easier which kind of address it is.

Add public properties to AddressType

---

src/Vlingo.Wire/Fdx/Inbound/InboundStreamInterest__Proxy.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Add InboundStreamInterest__Proxy

---

src/Vlingo.Wire/Node/AddressType.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Override ToString for AddressType in order to print properly

AddressType print improvement

---

src/Vlingo.Wire.Tests/Message/RawMessageTest.cs
src/Vlingo.Wire/Channel/ResponseSenderChannel__Proxy.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStream__Proxy.cs
src/Vlingo.Wire/Fdx/Outbound/IManagedOutboundChannelProvider.cs
src/Vlingo.Wire/Message/BasicConsumerByteBuffer.cs
src/Vlingo.Wire/Message/Converters.cs
src/Vlingo.Wire/Message/RawMessageHeader.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Fix issue with wrong length when copying RawMessageHeader bytes

---

src/Vlingo.Wire/Channel/ChannelReaderConsumer__Proxy.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

This is needed for `Vlingo-net-directory`

Add ChannelReaderConsumer__Proxy and bump version

---

src/Vlingo.Wire/Channel/ResponseSenderChannel__Proxy.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Change included generic proxies following Vlingo.Common proxy generation change.

Bumping dependencies for Vlingo.Common and Vlingo.Actors

---

src/Vlingo.Wire/Channel/SocketChannelSelectionReader.cs
src/Vlingo.Wire/Channel/SocketChannelWriter.cs
src/Vlingo.Wire/Fdx/Inbound/SocketChannelInboundReader.cs
src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannel.cs
src/Vlingo.Wire/Multicast/MulticastPublisherReader.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Fixed many issues around client server socket connectivity, when some connections were dropped because the reference to client connection was no longer kept by the server.

Many small fixes around sockets connectivity

---

src/Vlingo.Wire/Fdx/Inbound/SocketChannelInboundReader.cs
src/Vlingo.Wire/Multicast/MulticastPublisherReader.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Proper channel publisher disposition and message queue cleaning.

Small fixes

---

src/Vlingo.Wire/Channel/ChannelMessageDispatcher.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorActor.cs
src/Vlingo.Wire/Channel/SocketChannelWriter.cs
src/Vlingo.Wire/Fdx/Bidirectional/ClientRequestResponseChannel.cs
src/Vlingo.Wire/Fdx/Bidirectional/ServerRequestResponseChannelActor.cs
src/Vlingo.Wire/Fdx/Bidirectional/ServerRequestResponseChannel__Proxy.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStreamActor.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStream__Proxy.cs
src/Vlingo.Wire/Fdx/Inbound/SocketChannelInboundReader.cs
src/Vlingo.Wire/Fdx/Outbound/ApplicationOutboundStream__Proxy.cs
src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannel.cs
src/Vlingo.Wire/Multicast/MulticastPublisherReader.cs
src/Vlingo.Wire/Multicast/MulticastSubscriber.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Adapting logging replacing .Log (removed) by newer counterparts

Upgrade Vlingo.Common and Vlingo.Actors.

---

src/Vlingo.Wire/Channel/SocketChannelWriter.cs

implements APM for read Memory stream and send to stream

---

src/Vlingo.Wire/Vlingo.Wire.csproj

Update Vlingo.Actors to 0.4.7, Vlingo.Common to 0.5.5

Updates with new implementation of BasicCompletes

---

src/Vlingo.Wire/Channel/SocketChannelWriter.cs

Socket connect now connects asynchronously

---

.travis.yml
appveyor.yml
src/Vlingo.Wire.Tests/Vlingo.Wire.Tests.csproj
src/Vlingo.Wire/Channel/ChannelMessageDispatcher.cs
src/Vlingo.Wire/Channel/IRequestChannelConsumer.cs
src/Vlingo.Wire/Channel/MockChannelReaderConsumer.cs
src/Vlingo.Wire/Channel/SocketChannelSelectionProcessorActor.cs
src/Vlingo.Wire/Channel/SocketChannelWriter.cs
src/Vlingo.Wire/Fdx/Bidirectional/BasicClientRequestResponseChannel.cs
src/Vlingo.Wire/Fdx/Bidirectional/SecureClientRequestResponseChannel.cs
src/Vlingo.Wire/Fdx/Bidirectional/ServerRequestResponseChannelActor.cs
src/Vlingo.Wire/Fdx/Inbound/InboundStreamActor.cs
src/Vlingo.Wire/Fdx/Inbound/SocketChannelInboundReader.cs
src/Vlingo.Wire/Fdx/Outbound/ManagedOutboundSocketChannel.cs
src/Vlingo.Wire/Message/BasicConsumerByteBuffer.cs
src/Vlingo.Wire/Message/IConsumerByteBuffer.cs
src/Vlingo.Wire/Message/MessagePartsBuilder.cs
src/Vlingo.Wire/Multicast/MulticastSubscriber.cs
src/Vlingo.Wire/Vlingo.Wire.csproj

Along with netstandard2.0. Silence warnings

Target netstandard2.1
